import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  tela: { flex: 1, backgroundColor: "#0f172a" },
  mainGame: {
    flexGrow: 1,
    flexDirection: "column",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 20,
    gap: 20,
  },
  titulo: {
    marginTop: 10,
    fontSize: 50,
    color: "white",
    fontWeight: "bold",
    textAlign: "center",
  },
  playerContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    columnGap: 80,
    rowGap: 20,
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
  },
  player: {
    backgroundColor: "#1e293b",
    padding: 25,
    borderRadius: 16,
    alignItems: "center",
    minWidth: 220,
    maxWidth: "100%",
    // Sombra iOS
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.4,
    shadowRadius: 10,
    // Sombra Android
    elevation: 8,
  },
  playerTitulo: { fontSize: 24, fontWeight: "bold", color: "white" },
  soma: { fontSize: 18, color: "white", marginTop: 5 },
  dados: {
    flexDirection: "row",
    justifyContent: "center",
    gap: 10,
    marginVertical: 10,
  },
  dado: { fontSize: 70, color: "white" },
  dadoContainer: { flexDirection: "column", alignItems: "center", gap: 8 },
  valor: { fontSize: 20, fontWeight: "bold", color: "white" },
  botao: {
    marginTop: 10,
    paddingVertical: 8,
    paddingHorizontal: 15,
    minHeight: 44,
    justifyContent: "center",
    borderRadius: 8,
    backgroundColor: "#22c55e",
  },
  botaoDesabilitado: { backgroundColor: "gray" },
  botaoTexto: { color: "white", fontWeight: "bold" },
  resultado: { alignItems: "center", width: "100%" },
  resultadoTexto: { textAlign: "center", fontSize: 20, color: "white" },
  placar: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 20,
    justifyContent: "center",
    marginTop: 10,
  },
  placarTexto: { fontSize: 30, color: "white", textAlign: "center" },
  final: { marginTop: 15, alignItems: "center" },
  finalTexto: { fontSize: 30, textAlign: "center", color: "white" },
});
